substitutions:
  name: autovorm
  device_description: "Control Technivorm Moccamaster"

esp32:
  board: esp32dev
  framework: 
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

ota:

logger:
#  baud_rate: 0  # Disable UART logger if using UART0 (pins 1,3)
  level: DEBUG

switch:
  - platform: gpio
    pin: 32
    name: "Main Power"
    id: autovorm_main_power
